version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql:rw
      - ${MYSQL_CNF_PATH}:/etc/mysql/conf.d/my.cnf:rw
    networks:
      - backend
