version: '3.5'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql-data:
    driver: ${VOLUMES_DRIVER}
  mysql-my.cnf:
    driver: ${VOLUMES_DRIVER}

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - mysql-data:/var/lib/mysql:rw
      - mysql-my.cnf:/etc/mysql/conf.d/my.cnf:rw
    networks:
      - backend
