version: '3.8'
name: love-note-server

services:
  api:
    image: ${DOCKER_REGISTRY}/${ALIYUN_NAMESPACE}/love-note-backend:latest
    container_name: love-note-backend
    ports:
      - '${SERVER_PORT}:9315' # 直接暴露 API 端口
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RUNNING_ENV=prod
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mysql
      - redis
    networks:
      - love-note-network
    restart: unless-stopped

  mysql:
    image: 'mysql:8.0.30'
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql:rw
      - ${MYSQL_CNF_PATH}:/etc/mysql/conf.d/my.cnf:rw
    networks:
      - love-note-network
  redis:
    image: 'redis:latest'
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - love-note-network

networks:
  love-note-network:
    external: true
