SERVER_CONFIG:
  PORT: 9315 # 应用服务端口
MYSQL_CONFIG:
  USER: root
  PASSWORD: '123456'
  HOST: mysql
  PORT: 3306
  DATABASE: love_note
AUTH_CONFIG:
  JWT_SECRET: secret
  JWT_EXPIRES_IN: 1h
EMAIL_CONFIG:
  USER: 'user-email@xx.com'
  PASS: 'your-email-password'
REDIS_CONFIG:
  HOST: redis
  PORT: 6379
UPLOAD_CONFIG:
  MAX_FILE_SIZE: 10 # MB
  MAX_FILE_COUNT: 9
  DESTINATION: uploads
